applications:
  graphile:
    source:
      root: "/"
      operations:
        check-runtime:
          command: |
            set -e
            bash scripts/check-runtime.sh
    crons:
      check-runtime:
        # Run the code below every day at midnight.
        spec: '0 0 * * *'
        commands:
          start: |
            upsun source-operation:run check-runtime --no-wait --yes
    type: nodejs:20
    hooks:
      build: |
        set -e
        curl -fsS https://raw.githubusercontent.com/upsun/snippets/main/src/install-github-asset.sh | bash /dev/stdin "mikefarah/yq"
    web:
      commands:
        start: "node_modules/.bin/postgraphile"
    mounts:
      "/run": "shared:files/run"
      "/.cache": "shared:files/.cache"
    relationships:
      pg: "postgres:postgresql"
services:
  postgres:
    type: postgresql:16
    configuration:
      extensions:
        - uuid-ossp
routes:
  https://{default}/:
    type: upstream
    upstream: "graphile:http"
