applications:
  pg:
    source:
      root: "/"
    type: nodejs:20
    web:
      commands:
        start: "node_modules/.bin/postgraphile"
    mounts:
      "/run": "shared:files/run"
      "/.cache": "shared:files/.cache"
    relationships:
      pg: "postgres:postgresql"

services:
  postgres:
    type: postgresql:16
    disk: 1024
    configuration:
      extensions:
        - uuid-ossp