name: forestadmin
type: nodejs:18

build:
  flavor: none

relationships:
  pg: "postgres:postgresql"

hooks:
  build: |
    set -e
    npm install

web:
  commands:
    start: |
      set -e
      npm start

mounts:
  "/run": "shared:files/run"
  "/.cache": "shared:files/.cache"

disk: 1024
