name: forestadmin
type: nodejs:18
flavor: none

relationships:
  pg: "postgres:postgresql"

hooks:
  build:
    npm i
    npm run forest:login
    npm run forest:create
    cd pgadmin
    npm i -s

web:
  commands:
    start: |
      cd pgadmin
      npm run start:watch

mounts:
  "/run": "shared:files/run"
  "/.cache": "shared:files/.cache"

disk: 1024
