name: forestadmin
type: nodejs:18

build:
  flavor: none

variables:
  env:
    NODE_ENV: production
    NPM_CONFIG_PRODUCTION: false

relationships:
  pg: "postgres:postgresql"

hooks:
  build: |
    set -e
    npm install
  deploy: |
    set -e
    export NODE_ENV="development"
    node deploy.js

web:
  commands:
    start: |
      set -e
      npm start

mounts:
  "/run": "shared:files/run"
  "/.cache": "shared:files/.cache"

disk: 1024
